name: ci
run-name: Ci actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: checkout
        uses: actions/checkout@v4
      
      - 
        name: setup docker build
        uses: docker/setup-buildx-action@v3
        
      - 
       name: lint dockerfile
       uses: hadolint/hadolint-action@v3.1.0
       with:
         dockerfile: Dockerfile

      - 
        name: build docker file
        run: docker build . -t hive
      - 
        name: run container image
        run: docker run --name hive  --rm -d -p 8000:8000 hive 

      - 
        name: test docker container
        run: sleep 20; pytest  
      - 
        name: stop container
        run: docker stop hive
