name: ci
run-name: Ci actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: checkout
        uses: actions/checkout@v4
      
      - 
        name: setup docker build
        uses: docker/setup-buildx-action@v3
      
      - 
        name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - 
        name: python requirements
        run: pip install -r requirements.txt
      - 
       name: lint dockerfile
       uses: hadolint/hadolint-action@v3.1.0
       with:
         dockerfile: Dockerfile

      -  
        name: build docker file
        run: docker build . -t ahatem/DevopsHive:latest

      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}      

      -  
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ahatem/DevopsHive:latest
      - 
        name: run container image
        run: docker run --name hive  --rm -d -p 8000:8000 DevopsHive 

      - 
        name: test docker container
        run: sleep 20; pytest  
      - 
        name: stop container
        run: docker stop hive
